Add more logging in TonY client and related utils to see if TonY config can be overridden by other parallel jobs.
linkedin/TonY pull request #489
Opened 2020-12-11 06:41 UTC by burgerkingeater

We already have a PR(https://github.com/linkedin/TonY/pull/455) to address the issue where concurrent TonY jobs could override each other's local TonY config. However we are seeing  TonY job config is conflicting again. This PR adds more logging to help debugging this issue.

2020-12-11 07:20 UTC, oliverhu commented on tony-core/src/main/java/com/linkedin/tony/TonyClient.java
> +      LOG.info("TonY conf " + tonyFinalConf + " is created locally.");
make all these LOG.DEBUG, also change all port reserver/release DEBUG

2020-12-11 22:52 UTC, hungj approved these changes

2020-12-11 23:07 UTC, oliverhu requested changes
-1

2020-12-12 09:20 UTC, burgerkingeater commented
TonY config conflict is addressed by https://github.com/linkedin/TonY/pull/490/. So we don't need this debugging log any more.

2020-12-12 09:20 UTC, closed without merging